# Generated by Django 4.2.11 on 2025-08-17 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(blank=True, help_text="User's public RSA key")),
                ('private_key', models.TextField(blank=True, help_text="User's encrypted private RSA key")),
                ('key_created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('key_generation', 'Key Generation'), ('key_import', 'Key Import'), ('message_send', 'Message Send'), ('message_receive', 'Message Receive'), ('key_exchange', 'Key Exchange'), ('login', 'User Login'), ('logout', 'User Logout'), ('security_check', 'Security Check')], max_length=50)),
                ('log_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('file', 'File Attachment'), ('key_exchange', 'Key Exchange')], default='text', max_length=20)),
                ('encrypted_content', models.TextField(help_text='AES encrypted message content')),
                ('encrypted_aes_key', models.TextField(help_text='RSA encrypted AES key')),
                ('iv', models.TextField(help_text='Initialization vector for AES encryption')),
                ('signature', models.TextField(help_text='Digital signature for message verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, help_text='Original filename if file attachment', max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_type', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the exchange')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_exchanges', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Exchange',
                'verbose_name_plural': 'Key Exchanges',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_owner_username', models.CharField(help_text='Username of the key owner', max_length=150)),
                ('public_key', models.TextField(help_text='Imported public RSA key')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is currently active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Key',
                'verbose_name_plural': 'Public Keys',
                'unique_together': {('owner', 'key_owner_username')},
            },
        ),
    ]
