# Generated by Django 5.2.5 on 2025-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=True, help_text='Whether this message is encrypted'),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_aes_key',
            field=models.TextField(blank=True, help_text='RSA encrypted AES key', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(help_text='Message content (encrypted or plaintext)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='iv',
            field=models.TextField(blank=True, help_text='Initialization vector for AES encryption', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='signature',
            field=models.TextField(blank=True, help_text='Digital signature for message verification', null=True),
        ),
    ]
